[project]
name = "alle-freelancer-rechnungen"
version = "0.1.0"
description = "Rechnungsübersicht für Freelancer"
requires-python = ">=3.12"
dependencies = [
    "duckdb",
    "fastexcel>=0.20.1",
    "polars",
    "pydantic>=2.13.3",
    "python-dotenv",
    "riffq",
    "xlsxwriter>=3.2.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/alle_freelancer_rechnungen"]
